project:
  type: website
  output-dir: docs

website:
  title: "cooperevan"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume.qmd
        text: Resume
      - href: gym.qmd
        text: Gym Project

format:
  html:
    theme: styles.scss
    mainfont: Ancizar Serif
    linkcolor: orange
    toc: true
    page-layout: full

editor: visual

