project:
  type: website
  output-dir: docs

website:
  title: "cooperevan"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume.qmd
        text: Resume
      - project.qmd
      - href: gym.qmd
        text: Gym

format:
  html:
    theme: styles.scss
    linkcolor: orange
    toc: true
    page-layout: full

editor: visual

