---
title: "Gym Data Collection"
format: html
toc: false
execute: 
  message: FALSE
  warning: FALSE
---

For the past few months, I've been collecting data on my gym schedule to see if what workouts I do change my sleep schedule (in hours).

```{r, echo=FALSE}
library(tidyverse)
library(janitor)
library(ggridges)
library(PNWColors)
library(gt)
library(ggplot2)
```

### data table

```{r}
#here I cleaned and wrangled my data
stat_data <- read.csv("STATS workout data - Sheet1-5.csv") |> 
  clean_names() |> 
  rename(day = day_of_the_week, time = time_of_day_of_workout) |> 
  filter(exercise_type != "Sarms")

clean_data <- stat_data %>%
  mutate(exercise_type = na_if(exercise_type, "")) %>%
  drop_na(exercise_type)#dropped columns with no data, or NA


#gt table to show data
gt(clean_data)

```

```{r}
#ggplot data
ggplot(clean_data, 
aes(x = asleep, y = exercise_type, fill = exercise_type)) +
geom_density_ridges() +
theme_ridges() + 
theme(legend.position = "none",
      axis.title = element_text(color = "#00496FFF"), 
      axis.line = element_line(color = "#00496FFF"), 
      axis.text = element_text(color = "#00496FFF"), 
      axis.ticks = element_line(color = "#00496FFF"),
      plot.title = element_text(color = "#DD4124FF"))+
scale_fill_manual(values = PNWColors::pnw_palette("Bay", 5))+
labs(x = "Sleep (Hours)",
y = "Exercise",
title = "Workout Plot",
caption = "figure 1")
```

### the averages

Below are the average hours of sleep for each exercise.

```{r, echo=FALSE}
ggplot(clean_data,
       aes(x = exercise_type, y = asleep, color = exercise_type))+
  geom_boxplot()+ 
  geom_jitter()+
  scale_color_manual(values = PNWColors::pnw_palette("Bay", 5))+
  theme(
      axis.title = element_text(color = "#00496FFF"), 
      axis.line = element_line(color = "#00496FFF"), 
      axis.text = element_text(color = "#00496FFF"), 
      axis.ticks = element_line(color = "#00496FFF"),
      plot.title = element_text(color = "#DD4124FF"))+
  labs(x ="Exercise Type" ,
       y ="Time Asleep (hours)",
       title = "Mean Values for Exercise Type and Sleep Duration",
       caption = "figure 2")
```
