---
title: "RESUME"
format: html
---

**Evan Cooper**

Santa Barbara, CA \| 408 332-3923 \| ejc5502\@gmail.com \| [LinkedIn Profile](https://www.linkedin.com/in/evan-cooper-758619210/)

# **EDUCATION**

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

**University of California, Santa Barbara (UCSB)			           Expected: June. 2025**

Bachelors of Arts, Environmental Studies \| GPA 3.0

**West Valley Community College						Aug. 2020- May 2022**

Associates of Science, Ecology, Biodiv. & Conserv, AS \| GPA 3.8

# **EXPERIENCE**

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

**Team Shift Lead** \| Smitten Ice Cream (San Jose, CA)			**Dec. 2019- Aug 2020**

-   Managed staff in a high paced environment, assisting customers, collaborating with management of efficiency and revenue.

-   Analyzed finances, developed team scheduling, communicated clearly with coworkers.

-   Organized and maintained workplace, kept track of inventory and shipments.

-   Trained and mentored new employees.

**Animal Care Intern** \| Santa Barbara Wildlife Network (Santa Barbara)	**Apr 2023 - June 2023**

-   Hands-on experience with native wildlife performing feedings, distributing medication, monitoring hydration levels while gaining knowledge on zoology and morphology. 

-   Cared for 20+ animals a day (mammal and birds).

-   Organized feeding schedules, cleaned enclosures, and provided medical care to patients in a caring and professional manner. \

**Zoo Educator \|** Santa Barbara Zoo (Santa Barbara, CA) **Oct 2023 - Mar 2024**

-   Overlooking the wellbeing and safety of 10+ kids for 8 hours a day.

-   Provided in depth and thorough information on the wildlife, habitats, and history within the Santa Barbara Zoo.

-   Learned the importance of patience, cooperation, and providing upfront and clear expectations to ensure a mutually respected environment.\

**Server** \| Annisquam Yacht Club (Gloucester, MA)				**July 2024 - Sept 2024**

-   Provided professional, high quality customer service in a fast-paced environment to upscale clientele at a private yacht club.

-   Regularly tended to over 150 guests per night between 5 servers.

-   Maintained a full product knowledge of menu items that changed bi-weekly as well as nightly specials and entire cocktail menu.

-   Committed to providing a memorable dining experience with above and beyond service, resulting in high praise from guests and opportunities for further occupation from management.

-   Perpetuated effective communication with kitchen staff to ensure food quality and service for the guest.

**Volunteer** \| UCSBYourTrees (Santa Barbara, CA)

-   Planted trees across school campuses including UCSB and local middle schools. 

-   Gained a vast knowledge of local tree species and methods to care for them. 

-   Curated a detailed brochure for students to use to identify and locate trees on campus. 

-   Visited middle schools to teach kids about trees in their area and classification strategies. 

# **RELEVANT COURSEWORK**

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

**Environmental Impact Analysis 165A**

-   Studied the historical basis for Environmental impact assessment (EIA) and the difference between EIA and Land Suitability Assessments (LSA).

-   Learned the structure of EIA documents, how it provides for public disclosure and the implication of environmental consequences.

-   Curated our own Environmental Impact Assessment dealing with real world scenarios.

-   How EIA is used in short and long term decisions that shape our community and environment.

-   Gained an intimate understanding of the balance between economic development and environmental stewardship.

**Waste Management 172**

-   In depth understanding how local and global waste materials are managed and the interconnectedness with pollution, fast fashion, energy, health and climate change.

-   Gained access to the Santa Barbara waste processing facility and learned the day to day of dealing with waste.

**Sustainable Communities 116**

-   Learned about the root of our socioeconomic crisis and understood how we can make our world more sustainable.

**Ecosystem Biodiversity 101**

-   Became well versed in ecosystem services and the benefits of a healthy natural environment to improve economical, personal, and health issues we face.

-   Understanding the value of an interdisciplinary approach to ecological issues through examining natural science, social science, and humanities.

-   Learned about Traditional Ecological Knowledge from the descendants of the local chumash people of Santa Barbara and how we can build a connection between people and the land.

**Low Carbon Society**

-   Learned how to transition to a low carbon society with alterations pertaining to development, integrating knowledge about climate change science, responses to climate impacts, and the technological, behavioral and policy solutions needed for local and global transitions away from fossil fuels.

\

# **RELATED ENVIRONMENTAL EXPERIENCE**

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

**Studying Conservation in Peru and Galapagos Islands**  		**Jan 23rd - March 16th 2024**

-   Became well versed in the effect of Peruvian industries such as logging, mining and farming, and its impact to local biodiversity and residents in the most biodiverse habitat on the planet, the Amazon Rainforest.

-   Lead group forums with other environmental students debating solutions to local conservation issues from recent news articles at our location, including Giant River Otter Conservation, local indigenous tribe rights, and government policies on illegal logging and goldmining practices.

-   Hiked over five miles a day studying local flora and fauna documenting specimens daily  in a notebook for the entirety of the three month trip.

-   In a team conducted scientific research on vernal pool biodiversity and the importance of rain abundance for arthropod abundance at Cocha Cashu Biological Reservation (second most remote research station in the world).

# **PERSONAL INTERESTS**

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

**Surfing:** Grew up surfing in Santa Cruz at Pleasure Point and Steamers Lane. Spent time surfing on the island of Kauai and Hawaii, and most recently have been surfing in Santa Barbara County at Jalama and Devroux. Boards used are 6 ft chili and 7 ft midlength 

**Rock Climbing:** Climbing for five years, mainly in the Santa Cruz mountains at Castle Rock state park and Lizards Mouth in Santa Barbara. The highest grade climbed 5.11d, V6 boulder. Currently using top rope belay but working towards becoming efficient in lead climbing.

**Birdwatching:** Spent the last four years becoming proficient locating and identifying North American bird species, currently able to identify over 200+ birds from sight and sound. Favorite birds include the endangered Hawaiian Akepa (Akakane), Pileated Woodpecker in Santa Cruz mountains, King Vulture in Peru, California Condor in Pinnacles National Park, and the Belted Kingfisher, resident to the UCSB lagoon.

\
